pull_request_rules:
  - name: T24-MARKER
    conditions:
      - base = main
    actions:
      label:
        add: ["t24-marker"]
  - name: T24-SELF-MERGE
    conditions:
      - base = main
      - label = t24-marker
    actions:
      merge:
        method: squash
