pull_request_rules:
  - name: t24 queue trigger
    conditions:
      - base = main
      - label = t24-queue
    actions:
      queue:
        name: t24q
queue_rules:
  - name: t24q
    checks_timeout: 10 minutes
    merge_conditions:
      - check-success = t24-gate-head
